/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vin/{vin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vin: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VinInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    kind?: components["schemas"]["ComponentKind"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComponentSpec"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VehicleVariant"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file: components["schemas"]["IFormFile"];
                    } & {
                        role?: components["schemas"]["FileRole"];
                    } & {
                        label?: string;
                    } & {
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/files/{fileId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FileRoleBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HardwareBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/hardware/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    kind: components["schemas"]["ComponentKind"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["StartAnalysisBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SseItemOfJobEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnalysisReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/report.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/maps/{mapId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                    mapId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MapData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/hex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    offset?: number;
                    length?: number;
                };
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HexPageDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    mode: string;
                    q: string;
                    type?: components["schemas"]["DataType"];
                    endian?: components["schemas"]["Endianness"];
                };
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/dyno": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DynoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DynoResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InspectBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PointInspection"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/candidates/{candidateId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                    candidateId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecisionBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AIAnalysisResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/ai/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AskBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantAnswer"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysisId}/candidates/{candidateId}/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysisId: string;
                    candidateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MapHypothesisResult"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AIAnalysisResult: {
            findings: components["schemas"]["Finding"][];
            rejected: components["schemas"]["RejectedClaim"][];
            verifications: components["schemas"]["VerificationResult"][];
            consensus: components["schemas"]["ComponentConsensus"][];
            verdict: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number;
            contradictions: string[];
            missingData: string[];
            runs: components["schemas"]["AgentRun"][];
            usage: components["schemas"]["AIUsage"];
            model: string;
        };
        AIUsage: {
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            /** Format: int64 */
            cacheReadTokens: number;
            /** Format: int64 */
            cacheWriteTokens: number;
        };
        AgentRun: {
            agent: string;
            fromCache: boolean;
            usage: components["schemas"]["AIUsage"];
            /** Format: int32 */
            accepted: number;
            /** Format: int32 */
            rejected: number;
            error: null | string;
        };
        AnalysisReport: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId?: null | string;
            /** Format: date-time */
            createdAt: string;
            analysisVersion: string;
            modifiedSha256: string;
            stockSha256?: null | string;
            modifiedName: string;
            stockName?: null | string;
            detection: components["schemas"]["DetectionResult"];
            ecu: components["schemas"]["EcuIdentification"];
            checksums: components["schemas"]["ChecksumReport"];
            vehicle: components["schemas"]["VehicleResolution"];
            dataAvailability: components["schemas"]["DataAvailability"];
            definitionSource: string;
            definitionNotes: string[];
            maps: components["schemas"]["MapSummary"][];
            candidates: components["schemas"]["MapCandidate"][];
            modifiedMaps: components["schemas"]["DiffSummary"][];
            /** Format: int32 */
            changedBytes: number;
            unmappedChanges: components["schemas"]["UnmappedChange"][];
            calibrationFindings: components["schemas"]["Finding"][];
            dependencies: components["schemas"]["DependencyGraph"];
            simulation: components["schemas"]["SimulationSummary"];
            risk: components["schemas"]["RiskReport"];
            explanations: components["schemas"]["MapExplanation"][];
            keyMetrics: components["schemas"]["KeyMetric"][];
            mainFindings: components["schemas"]["MainFinding"][];
            unknowns: string[];
            disclaimer: null | string;
        };
        AskBody: {
            question: string;
            selection: null | components["schemas"]["JsonElement"];
        };
        AssistantAnswer: {
            answer: string;
            /** Format: double */
            confidence: number;
            evidence: components["schemas"]["Evidence"][];
            assumptions: string[];
            unknowns: string[];
            suggestedChecks: string[];
            fromCache: boolean;
            /** Format: int32 */
            rejectedEvidence: number;
        };
        AxisGuess: {
            quantity: components["schemas"]["AxisQuantity"];
            /** Format: double */
            likelihood: number;
            /** Format: double */
            factor: number;
            unit: string;
        };
        /** @enum {unknown} */
        AxisQuantity: "Unknown" | "EngineSpeed" | "PedalPosition" | "InjectionQuantity" | "AtmosphericPressure" | "AirMass" | "Torque" | "Gear" | "Temperature" | "BoostPressure" | "Index";
        ByteRange: {
            /** Format: int32 */
            start: number;
            /** Format: int32 */
            length: number;
            /** Format: int32 */
            end: number;
        };
        /** @enum {unknown} */
        CandidateStatus: "Candidate" | "Confirmed" | "Rejected";
        ChecksumBlock: {
            name: string;
            /** Format: int32 */
            start: number;
            /** Format: int32 */
            end: number;
            algorithm: string;
            status: components["schemas"]["ChecksumStatus"];
            stored?: null | string;
            computed?: null | string;
        };
        ChecksumReport: {
            overall: components["schemas"]["ChecksumStatus"];
            blocks: components["schemas"]["ChecksumBlock"][];
            note: string;
        };
        /** @enum {unknown} */
        ChecksumStatus: "Valid" | "Invalid" | "NotImplemented" | "Unknown";
        ComponentConsensus: {
            component: string;
            physicsSeverity: components["schemas"]["Severity"];
            finalSeverity: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number;
            /** Format: double */
            agreement: number;
            votes: components["schemas"]["ComponentVote"][];
            rationale: string;
        };
        /** @enum {unknown} */
        ComponentKind: "Engine" | "Turbo" | "Injectors" | "FuelSystem" | "Transmission" | "Clutch" | "Intercooler" | "Sensors" | "Emissions";
        ComponentMargin: {
            component: string;
            label: string;
            metric: string;
            load: components["schemas"]["Estimate"];
            limit: components["schemas"]["Param"];
            utilization: components["schemas"]["Estimate"];
            margin: components["schemas"]["Estimate"];
            /** Format: double */
            changeVsStockPct?: number;
            loadLevel: components["schemas"]["LoadLevel"];
            severity: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number;
            showExactUtilization: boolean;
            critical: boolean;
            explanation: string;
            affectedRpm?: null | (number)[];
            relatedMaps: string[];
            missingData: string[];
            evidence: components["schemas"]["Evidence"][];
        };
        ComponentSpec: {
            id: string;
            kind: components["schemas"]["ComponentKind"];
            name: string;
            source: components["schemas"]["SourceType"];
            /** Format: double */
            confidence: number;
            userVerified: boolean;
            isOverride: boolean;
            parameters: {
                [key: string]: components["schemas"]["Param"];
            };
            note?: null | string;
        };
        ComponentVote: {
            source: string;
            severity: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number;
        };
        /** @enum {unknown} */
        ConfidenceLevel: "Unknown" | "Low" | "LowMedium" | "Medium" | "MediumHigh" | "High";
        /** @enum {unknown} */
        CoolantState: "Cold" | "Normal" | "Hot";
        CreateProjectBody: {
            name: string;
            vin: null | string;
            notes: null | string;
        };
        DataAvailability: {
            level: components["schemas"]["ConfidenceLevel"];
            /** Format: double */
            score: number;
            factors: string[];
        };
        /** @enum {unknown} */
        DataType: "UInt8" | "Int8" | "UInt16" | "Int16" | "UInt32" | "Int32" | "Float32";
        DecisionBody: {
            decision: string;
            role: null | string;
            note: null | string;
        };
        DependencyEdge: {
            from: string;
            to: string;
            relation: string;
        };
        DependencyGraph: {
            nodes: components["schemas"]["DependencyNode"][];
            edges: components["schemas"]["DependencyEdge"][];
        };
        DependencyNode: {
            id: string;
            label: string;
            kind: components["schemas"]["NodeKind"];
            role: null | components["schemas"]["MapRole"];
            mapId: null | string;
            state: components["schemas"]["NodeState"];
            detail: null | string;
        };
        DetectionResult: {
            pluginId: string;
            /** Format: double */
            score: number;
            reasons: string[];
        };
        DiffSummary: {
            mapId: string;
            name: string;
            role: components["schemas"]["MapRole"];
            /** Format: int32 */
            changedCells: number;
            /** Format: int32 */
            totalCells: number;
            /** Format: double */
            meanDeltaPct: number;
            /** Format: double */
            maxDeltaPct: number;
            /** Format: double */
            stockMax: number;
            /** Format: double */
            modMax: number;
            unit: string;
            /** Format: double */
            meanRatio: number;
        };
        DynoCurve: {
            label: string;
            points: components["schemas"]["PointResult"][];
            peakPowerHp: components["schemas"]["Estimate"];
            /** Format: double */
            peakPowerRpm: number;
            peakTorque: components["schemas"]["Estimate"];
            /** Format: double */
            peakTorqueRpm: number;
        };
        DynoRequest: {
            /** Format: int32 */
            gear: number;
            /** Format: double */
            rpmStart: number;
            /** Format: double */
            rpmEnd: number;
            /** Format: double */
            rpmStep: number;
            /** Format: double */
            throttlePct: number;
            /** Format: double */
            ambientTempC: number;
            /** Format: double */
            atmosphericPressureMbar?: number;
            /** Format: double */
            altitudeM: number;
            environment: components["schemas"]["EnvironmentConditions"];
        };
        DynoResult: {
            request: components["schemas"]["DynoRequest"];
            stock: null | components["schemas"]["DynoCurve"];
            modified: components["schemas"]["DynoCurve"];
            assumptions: string[];
            disclaimer: null | string;
        };
        EcuIdentification: {
            pluginId: string;
            ecuFamily: string;
            manufacturer: string;
            boschNumber: components["schemas"]["Param"];
            oemPartNumber: components["schemas"]["Param"];
            hardwareNumber: components["schemas"]["Param"];
            softwareNumber: components["schemas"]["Param"];
            softwareVersion: components["schemas"]["Param"];
            engineCode: components["schemas"]["Param"];
            processor: string;
            endianness: components["schemas"]["Endianness"];
            /** Format: int32 */
            flashSize: number;
            sections: components["schemas"]["MemorySection"][];
            /** Format: double */
            confidence: number;
            notes: string[];
        };
        /** @enum {unknown} */
        Endianness: "Big" | "Little";
        EnvironmentConditions: {
            /** Format: double */
            ambientTempC: number;
            /** Format: double */
            altitudeM: number;
            /** Format: double */
            atmosphericPressureMbar?: number;
            coolant: components["schemas"]["CoolantState"];
            /** Format: double */
            pressureMbar: number;
        };
        Estimate: {
            /** Format: double */
            value?: number;
            /** Format: double */
            low?: number;
            /** Format: double */
            high?: number;
            unit: string;
            /** Format: double */
            confidence: number;
            kind: components["schemas"]["ValueKind"];
            note?: null | string;
        };
        Evidence: {
            type: components["schemas"]["EvidenceType"];
            ref: string;
            detail: string;
        };
        /** @enum {unknown} */
        EvidenceType: "Map" | "Diff" | "Simulation" | "Component" | "KnowledgeBase" | "Rule" | "Log" | "Binary";
        /** @enum {unknown} */
        FileRole: "Stock" | "Modified" | "Version";
        FileRoleBody: {
            role: components["schemas"]["FileRole"];
        };
        Finding: {
            code: string;
            text: string;
            severity: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number;
            evidence: components["schemas"]["Evidence"][];
            assumptions: string[];
            unknowns: string[];
            affectedComponents: string[];
            relatedMaps: string[];
            source: components["schemas"]["FindingSource"];
            sourceDetail?: null | string;
            rpmRange?: null | (number)[];
        };
        /** @enum {unknown} */
        FindingSource: "Rule" | "Physics" | "Risk" | "AI" | "Consensus";
        HardwareBody: {
            overrides: components["schemas"]["HardwareOverride"][];
        };
        HardwareOverride: {
            kind: components["schemas"]["ComponentKind"];
            catalogId?: null | string;
            custom?: null | components["schemas"]["ComponentSpec"];
            note?: null | string;
        };
        HardwareProfile: {
            engine: components["schemas"]["ComponentSpec"];
            turbo: components["schemas"]["ComponentSpec"];
            injectors: components["schemas"]["ComponentSpec"];
            fuelSystem: components["schemas"]["ComponentSpec"];
            transmission: components["schemas"]["ComponentSpec"];
            clutch: components["schemas"]["ComponentSpec"];
            intercooler: components["schemas"]["ComponentSpec"];
            sensors: components["schemas"]["ComponentSpec"];
            emissions: components["schemas"]["ComponentSpec"];
            all: null | components["schemas"]["ComponentSpec"][];
        };
        HexPageDto: {
            /** Format: int32 */
            offset: number;
            /** Format: int32 */
            length: number;
            /** Format: int32 */
            fileSize: number;
            modified: string;
            stock: null | string;
            regions: components["schemas"]["HexRegion"][];
            changed: components["schemas"]["ByteRange"][];
        };
        HexRegion: {
            /** Format: int32 */
            start: number;
            /** Format: int32 */
            end: number;
            kind: string;
            label: string;
            mapId: null | string;
        };
        /** Format: binary */
        IFormFile: string;
        InspectBody: {
            /** Format: double */
            rpm: number;
            /** Format: double */
            pedalPct: number;
            /**
             * Format: int32
             * @default 4
             */
            gear: number;
            /**
             * Format: double
             * @default 20
             */
            ambientTempC: number;
            /**
             * Format: double
             * @default 0
             */
            altitudeM: number;
            /** Format: double */
            atmosphericPressureMbar?: number;
            coolant: components["schemas"]["CoolantState"];
        };
        JobEvent: {
            /** Format: uuid */
            jobId: string;
            kind: string;
            step: null | components["schemas"]["StepProgress"];
            status: components["schemas"]["JobStatus"];
            error?: null | string;
            /** Format: uuid */
            analysisId?: null | string;
        };
        JobState: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["JobStatus"];
            events: components["schemas"]["JobEvent"][];
        };
        /** @enum {unknown} */
        JobStatus: "Queued" | "Running" | "Completed" | "Failed";
        JsonElement: unknown;
        KeyMetric: {
            id: string;
            label: string;
            stock: null | components["schemas"]["Estimate"];
            modified: components["schemas"]["Estimate"];
            detail?: null | string;
            severity?: null | components["schemas"]["Severity"];
            link?: null | string;
        };
        /** @enum {unknown} */
        Limiter: "None" | "DriverWish" | "TorqueLimiter" | "GearLimiter" | "ConversionAxisEnd" | "SmokeLimiter" | "BoostTarget" | "BoostLimiter" | "Svbl" | "Spool";
        /** @enum {unknown} */
        LoadLevel: "Unknown" | "Low" | "Moderate" | "High" | "VeryHigh";
        MainFinding: {
            text: string;
            severity: components["schemas"]["Severity"];
            link: null | string;
            code: string;
        };
        MapCandidate: {
            id: string;
            /** Format: int32 */
            address: number;
            /** Format: int32 */
            headerAddress: number;
            /** Format: int32 */
            rows: number;
            /** Format: int32 */
            cols: number;
            dataType: components["schemas"]["DataType"];
            endian: components["schemas"]["Endianness"];
            xAxisRaw: (number)[];
            yAxisRaw: (number)[];
            /** Format: double */
            rawMin: number;
            /** Format: double */
            rawMax: number;
            xAxisGuesses: components["schemas"]["AxisGuess"][];
            yAxisGuesses: components["schemas"]["AxisGuess"][];
            hypotheses: components["schemas"]["RoleHypothesis"][];
            status: components["schemas"]["CandidateStatus"];
            confirmedRole?: null | components["schemas"]["MapRole"];
            decisionNote?: null | string;
            best?: components["schemas"]["RoleHypothesis"];
            /** Format: int32 */
            xAxisAddress: number;
            /** Format: int32 */
            yAxisAddress: number;
        };
        /** @enum {unknown} */
        MapCategory: "Torque" | "Fuel" | "Air" | "Protection" | "Unknown";
        MapData: {
            id: string;
            summary: components["schemas"]["MapSummary"];
            xAxis: (number)[];
            yAxis: (number)[];
            values: (number)[];
            stockValues: null | (number)[];
            stockXAxis: null | (number)[];
            stockYAxis: null | (number)[];
            rawBytesAddress: null | number[];
        };
        MapExplanation: {
            mapId: string;
            name: string;
            whatChanged: string;
            purpose: string;
            linkedTo: string[];
            physicalEffect: string;
            affectedComponents: string[];
            assessment: string;
            severity: components["schemas"]["Severity"];
            dataToIncreaseConfidence: string[];
        };
        MapHypothesisResult: {
            role: string;
            /** Format: double */
            confidence: number;
            rationale: string;
            evidence: components["schemas"]["Evidence"][];
        };
        /** @enum {unknown} */
        MapRole: "Unknown" | "DriverWish" | "TorqueLimiter" | "GearTorqueLimiter" | "TorqueToIq" | "SmokeLimiter" | "BoostTarget" | "BoostLimiter" | "Svbl" | "VntDuty" | "Soi" | "Duration" | "RailPressure" | "LambdaTarget" | "EgtProtection" | "TemperatureProtection" | "RpmLimiter" | "GearboxTorqueMonitor";
        MapSummary: {
            id: string;
            name: string;
            role: components["schemas"]["MapRole"];
            category: components["schemas"]["MapCategory"];
            /** Format: int32 */
            address: number;
            /** Format: int32 */
            rows: number;
            /** Format: int32 */
            cols: number;
            dataType: components["schemas"]["DataType"];
            endian: components["schemas"]["Endianness"];
            /** Format: double */
            factor: number;
            /** Format: double */
            offset: number;
            unit: string;
            xAxis: string;
            yAxis: string;
            source: components["schemas"]["SourceType"];
            /** Format: double */
            confidence: number;
            modified: boolean;
            /** Format: double */
            modifiedPct: number;
            /** Format: double */
            maxDeltaPct: number;
            /** Format: int32 */
            dependencyCount: number;
            whyItMatters: string;
            /** Format: double */
            min: number;
            /** Format: double */
            max: number;
        };
        MemorySection: {
            name: string;
            /** Format: int32 */
            start: number;
            /** Format: int32 */
            end: number;
            kind: components["schemas"]["SectionKind"];
            source: components["schemas"]["SourceType"];
            /** Format: double */
            confidence: number;
            note?: null | string;
            /** Format: int32 */
            length: number;
        };
        ModelEstimate: {
            model: string;
            description: string;
            /** Format: double */
            torqueNm: number;
            /** Format: double */
            low: number;
            /** Format: double */
            high: number;
            /** Format: double */
            confidence: number;
            available: boolean;
            note: null | string;
        };
        /** @enum {unknown} */
        NodeKind: "Map" | "Quantity";
        /** @enum {unknown} */
        NodeState: "Stock" | "Modified" | "Warning" | "Danger" | "Unknown" | "NotApplicable";
        OperatingPoint: {
            /** Format: double */
            rpm: number;
            /** Format: double */
            pedalPct: number;
            /** Format: int32 */
            gear: number;
        };
        Param: {
            /** Format: double */
            number?: number;
            text?: null | string;
            unit: string;
            source: components["schemas"]["SourceType"];
            /** Format: double */
            confidence: number;
            userVerified: boolean;
            note?: null | string;
        };
        PluginInfo: {
            id: string;
            name: string;
            families: string[];
            commonRail: boolean;
        };
        PointInspection: {
            modified: components["schemas"]["PointResult"];
            stock: null | components["schemas"]["PointResult"];
        };
        PointResult: {
            point: components["schemas"]["OperatingPoint"];
            environment: components["schemas"]["EnvironmentConditions"];
            requestedTorque: components["schemas"]["Estimate"];
            permittedTorque: components["schemas"]["Estimate"];
            torqueLimiter: components["schemas"]["Limiter"];
            fuelLimiter: components["schemas"]["Limiter"];
            boostLimiter: components["schemas"]["Limiter"];
            iqRequested: components["schemas"]["Estimate"];
            iq: components["schemas"]["Estimate"];
            boostTarget: components["schemas"]["Estimate"];
            map: components["schemas"]["Estimate"];
            pressureRatio: components["schemas"]["Estimate"];
            compressorOutletTemp: components["schemas"]["Estimate"];
            intakeManifoldTemp: components["schemas"]["Estimate"];
            airMass: components["schemas"]["Estimate"];
            airFlow: components["schemas"]["Estimate"];
            correctedAirFlow: components["schemas"]["Estimate"];
            lambda: components["schemas"]["Estimate"];
            soi: components["schemas"]["Estimate"];
            duration: components["schemas"]["Estimate"];
            railPressure: components["schemas"]["Estimate"];
            torque: components["schemas"]["Estimate"];
            powerKw: components["schemas"]["Estimate"];
            powerHp: components["schemas"]["Estimate"];
            egt: components["schemas"]["Estimate"];
            models: components["schemas"]["ModelEstimate"][];
            beyondCalibratedRange: boolean;
            trace?: null | components["schemas"]["TraceStep"][];
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            vin?: null | string;
            preferredVariantId?: null | string;
            transmissionId?: null | string;
            hardwareOverrides: components["schemas"]["HardwareOverride"][];
            files: components["schemas"]["ProjectFile"][];
            notes?: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            headline?: null | components["schemas"]["ProjectHeadline"];
            /** Format: int32 */
            logCount: number;
            /** Format: int32 */
            simulationCount: number;
            /** Format: uuid */
            latestAnalysisId?: null | string;
        };
        ProjectFile: {
            /** Format: uuid */
            id: string;
            name: string;
            label: string;
            role: components["schemas"]["FileRole"];
            sha256: string;
            /** Format: int32 */
            size: number;
            /** Format: date-time */
            uploadedAt: string;
            notes?: null | string;
            summary?: null | components["schemas"]["VersionSummary"];
        };
        ProjectHeadline: {
            vehicle: null | string;
            engineCode: null | string;
            ecu: null | string;
            risk: null | components["schemas"]["Severity"];
        };
        RejectedClaim: {
            agent: string;
            text: string;
            reason: string;
        };
        RiskReport: {
            components: components["schemas"]["ComponentMargin"][];
            findings: components["schemas"]["Finding"][];
            overall: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number;
            criticalUnknowns: string[];
            overallExplanation: string;
        };
        RoleHypothesis: {
            role: components["schemas"]["MapRole"];
            /** Format: double */
            confidence: number;
            rationale: string;
            source: components["schemas"]["SourceType"];
            evidence: components["schemas"]["Evidence"][];
        };
        ScenarioSummary: {
            id: string;
            label: string;
            peakPowerHp: components["schemas"]["Estimate"];
            peakTorqueNm: components["schemas"]["Estimate"];
            maxEgtC: components["schemas"]["Estimate"];
            minLambda: components["schemas"]["Estimate"];
            maxPressureRatio: components["schemas"]["Estimate"];
        };
        /** @enum {unknown} */
        SectionKind: "Boot" | "Code" | "Calibration" | "Data" | "Empty" | "Unknown";
        /** @enum {unknown} */
        Severity: "Safe" | "Review" | "Warning" | "Danger" | "Unknown";
        SimulationSummary: {
            modifiedWot: components["schemas"]["WotSample"][];
            stockWot?: null | components["schemas"]["WotSample"][];
            scenarios: components["schemas"]["ScenarioSummary"][];
            /** Format: int32 */
            evaluatedPoints: number;
            assumptions: string[];
        };
        /** @enum {unknown} */
        SourceType: "OemSpec" | "PublicSpec" | "Database" | "VariantTypical" | "VinDecode" | "EcuBinary" | "Damos" | "A2L" | "Xdf" | "DefinitionDb" | "SignatureScan" | "DiagnosticLog" | "Calculated" | "AIInferred" | "User" | "Assumption" | "Unknown";
        SseItemOfJobEvent: {
            data?: components["schemas"]["JobEvent"];
            eventType: null | string;
            eventId?: null | string;
            reconnectionInterval?: null | string;
        };
        StartAnalysisBody: {
            /** Format: uuid */
            modifiedFileId: null | string;
            /** Format: uuid */
            stockFileId: null | string;
        };
        StepProgress: {
            step: string;
            label: string;
            state: components["schemas"]["StepState"];
            /** Format: double */
            fraction?: number;
            message?: null | string;
        };
        /** @enum {unknown} */
        StepState: "Pending" | "Running" | "Done" | "Skipped" | "Failed";
        SystemInfo: {
            version: string;
            aiConfigured: boolean;
            plugins: components["schemas"]["PluginInfo"][];
        };
        TraceStep: {
            quantity: string;
            formula: string;
            /** Format: double */
            value: number;
            unit: string;
            mapId?: null | string;
            note?: null | string;
        };
        UnmappedChange: {
            /** Format: int32 */
            start: number;
            /** Format: int32 */
            length: number;
            section: components["schemas"]["SectionKind"];
            nearestMapId: null | string;
        };
        UpdateProjectBody: {
            name: null | string;
            vin: null | string;
            notes: null | string;
            preferredVariantId: null | string;
            transmissionId: null | string;
        };
        /** @enum {unknown} */
        ValueKind: "Estimated" | "EcuRequested" | "Measured" | "Spec" | "Assumed" | "Unknown" | "NotApplicable";
        VariantCandidate: {
            variant: components["schemas"]["VehicleVariant"];
            /** Format: double */
            probability: number;
            reasons: string[];
        };
        VehicleProfile: {
            make: components["schemas"]["Param"];
            model: components["schemas"]["Param"];
            modelYear: components["schemas"]["Param"];
            vin: components["schemas"]["Param"];
            platform: components["schemas"]["Param"];
            engineCode: components["schemas"]["Param"];
            variantId?: null | string;
            /** Format: double */
            variantProbability: number;
            hardware: components["schemas"]["HardwareProfile"];
            overrides: components["schemas"]["HardwareOverride"][];
            notes: string[];
            profileHash: null | string;
        };
        VehicleResolution: {
            vin: null | components["schemas"]["VinInfo"];
            candidates: components["schemas"]["VariantCandidate"][];
            profile: components["schemas"]["VehicleProfile"];
        };
        VehicleVariant: {
            id: string;
            make: string;
            model: string;
            wmi: string[];
            platformCodes: string[];
            /** Format: int32 */
            yearFrom: number;
            /** Format: int32 */
            yearTo: number;
            engineCode: string;
            engineFamily: string;
            ecuPlugins: string[];
            components: {
                [key: string]: string;
            };
            transmissionOptions: string[];
            note?: null | string;
        };
        VerificationResult: {
            claim: string;
            agent: string;
            verdict: string;
            /** Format: double */
            confidence: number;
            rationale: string;
        };
        VersionSummary: {
            /** Format: int32 */
            changedMaps: number;
            peakPowerHp: null | components["schemas"]["Estimate"];
            peakTorqueNm: null | components["schemas"]["Estimate"];
            risk: components["schemas"]["Severity"];
            /** Format: double */
            confidence: number;
            /** Format: uuid */
            analysisId: string;
        };
        VinInfo: {
            vin: string;
            wmi: string;
            manufacturer?: null | string;
            region?: null | string;
            vds: string;
            platformCode?: null | string;
            /** Format: int32 */
            modelYear?: null | number;
            /** Format: char */
            plantCode: string;
            serial: string;
            checkDigitValid?: null | boolean;
            warnings: string[];
        };
        WotSample: {
            /** Format: double */
            rpm: number;
            torqueNm: components["schemas"]["Estimate"];
            powerHp: components["schemas"]["Estimate"];
            boostMbar: components["schemas"]["Estimate"];
            iqMg: components["schemas"]["Estimate"];
            lambda: components["schemas"]["Estimate"];
            egtC: components["schemas"]["Estimate"];
            torqueLimiter: components["schemas"]["Limiter"];
            fuelLimiter: components["schemas"]["Limiter"];
            boostLimiter: components["schemas"]["Limiter"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
